### ISSUE TITLE
Roadmap 2021

### ISSUE THREAD

**Issue by evpobr** [libsndfile/libsndfile#686]
- [x] New minor release (#692)
- [x] Replace `CHANGELOG` with `CHANGELOG.md`
- [ ] MP3 support (#499)
- [ ] WavPack support (#661)
- [ ] New open function

## New open function

```c
int sf_open_path(const char *name, int mode, SF_INFO *sfinfo, SF_OPEN_CONFIG *sfconf, SNDFILE **sndfile);
```

Returns error, uses no static variables.

```c
struct SF_OPEN_CONFIG
{
    int struct_size;
    int flags;
    ...
};
```

Flags:

* `SF_OPEN_UTF8_PATH` - path is UTF8 for Windows platform.
